version: '2'

services:

  biap-bap-protocol:
    build:
      context: biab-bap-protocol
      dockerfile: dockerfile
    container_name: bap-protocol
    depends_on:
      - mongo
    environment:
      ENV: dev
      DATABASE_URL: mongodb://mongo:27017
    expose:
      - 9002
    ports:
      - 9002:9002

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  biap-bap-client:
    build:
      context: biab-bap-client
      dockerfile: dockerfile
    container_name: bap-client
    depends_on:
      - biap-bap-protocol
    environment:
      ENV: dev
      PROTOCOL_HOST: buyer-app.ondc.org
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 9001:9001
    expose:
      - 9001

  mmi-client:
    build:
      context: ondc-mmi-service/webserver
      dockerfile: Dockerfile
    container_name: map-client
    environment:
      ENV: prod
      MMI_CLIENT_ID: ${MMI_CLIENT_ID}
      MMI_CLIENT_SECRET: ${MMI_CLIENT_SECRET}
      MMI_ADVANCE_API_KEY: ${MMI_ADVANCE_API_KEY}
      KNOWLARITY_NUMBER: ${KNOWLARITY_NUMBER}
      KNOWLARITY_AGENT_NUMBER: ${KNOWLARITY_AGENT_NUMBER}
      KNOWLARITY_API_KEY: ${KNOWLARITY_API_KEY}
      KNOWLARITY_AUTHORIZATION_HEADER_KEY: ${KNOWLARITY_AUTHORIZATION_HEADER_KEY}
    ports:
      - 8000:8000
    expose:
      - 8000

  nginx:
    build:
      context: biap-app-ui-front
      dockerfile: DockerfileWithoutSSL
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
        REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
        REACT_APP_JUSTPAY_CLIENT_AND_MERCHANT_KEY: ${REACT_APP_JUSTPAY_CLIENT_AND_MERCHANT_KEY}
        REACT_APP_MERCHANT_KEY_ID: ${REACT_APP_MERCHANT_KEY_ID}
        REACT_APP_PAYMENT_SDK_ENV: ${REACT_APP_PAYMENT_SDK_ENV}
        REACT_APP_PAYMENT_SERVICE_URL: ${REACT_APP_PAYMENT_SERVICE_URL}
    container_name: biap-app-ui-front
    #    depends_on:
    #      - biap-bap-client
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
      REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
    depends_on:
      - mmi-client
      - biap-client-node-js
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  biap-client-node-js:
    build:
      context: biap-client-node-js
      dockerfile: Dockerfile
      args:
        JUSPAY_SECRET_KEY_PATH: ${JUSPAY_SECRET_KEY_PATH}
        JUSPAY_BASE_URL: ${JUSPAY_BASE_URL}
        JUSPAY_MERCHANT_ID: ${JUSPAY_MERCHANT_ID}
        JUSPAY_API_KEY: ${JUSPAY_API_KEY}
        FIREBASE_ADMIN_SERVICE_ACCOUNT: ${FIREBASE_ADMIN_SERVICE_ACCOUNT}
        ONDC_BASE_API_URL: ${ONDC_BASE_API_URL}
        JUSPAY_WEBHOOK_USERNAME: ${JUSPAY_WEBHOOK_USERNAME}
        JUSPAY_WEBHOOK_PASSWORD: ${JUSPAY_WEBHOOK_PASSWORD}
        DOMAIN: ${DOMAIN}
        CITY: ${CITY}
        COUNTRY: ${COUNTRY}
        BAP_ID: "buyer-app.ondc.org"
        BAP_URL: ${BAP_URL}
        PROTOCOL_BASE_URL: ${PROTOCOL_BASE_URL}
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        BPP_PRIVATE_KEY: ${BPP_PRIVATE_KEY}
        BPP_PUBLIC_KEY: ${BPP_PUBLIC_KEY}
        BPP_UNIQUE_KEY_ID: ${BPP_UNIQUE_KEY_ID}
        PORT: 3000
        NODE_DEV: dev
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongo

  py-ondc-protocol:
    build:
      context: py-ondc-protocol/webserver
      dockerfile: Dockerfile
    container_name: py-ondc-protocol
    environment:
      ENV: prod
      MONGO_DATABASE_HOST: mongo
      BAP_URL: ${BAP_URL}
    ports:
      - 5555:5555
    expose:
      - 5555


