version: '2'

services:

  biap-bap-protocol:
    build:
      context: biab-bap-protocol
      dockerfile: dockerfile
    container_name: bap-protocol
    depends_on:
      - mongo
    environment:
      ENV: dev
    expose:
      - 9002
    ports:
      - 9002:9002

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  biap-bap-client:
    build:
      context: biab-bap-client
      dockerfile: dockerfile
    container_name: bap-client
    depends_on:
      - biap-bap-protocol
    environment:
      ENV: dev
      PROTOCOL_HOST: 139.59.24.32:9002
    ports:
      - 9001:9001
    expose:
      - 9001

  biap-bap-store-front-ui:
    build:
      context: biap-app-ui-front
      dockerfile: Dockerfile
    container_name: biap-app-ui-front
    #    depends_on:
    #      - biap-bap-client
    environment:
      REACT_APP_BASE_URL: http://ondc-sandbox.dataorc.in/
      REACT_APP_FIREBASE_API_KEY: AIzaSyAKeCcx6Y5WoSJbDb2LrFg3IO66o3VE4uM
      REACT_APP_FIREBASE_AUTH_DOMAIN: ondc-ui.firebaseapp.com
      REACT_APP_GOOGLE_API_KEY: AIzaSyCNDEZpMQN4xJwN3SKVyvRRw-e8Aj1Mca8
    expose:
      - 80
    ports:
      - 80:80