version: '2'

services:

  biap-bap-protocol:
    build:
      context: biab-bap-protocol
      dockerfile: dockerfile
    container_name: bap-protocol
    depends_on:
      - mongo
    environment:
      ENV: dev
      DATABASE_URL: mongodb://mongo:27017
    expose:
      - 9002
    ports:
      - 9002:9002

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  biap-bap-client:
    build:
      context: biab-bap-client
      dockerfile: dockerfile
    container_name: bap-client
    depends_on:
      - biap-bap-protocol
    environment:
      ENV: dev
      PROTOCOL_HOST: 13.235.14.111:9002
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 9001:9001
    expose:
      - 9001

  mmi-client:
    build:
      context: ondc-mmi-service/webserver
      dockerfile: Dockerfile
    container_name: map-client
    environment:
      ENV: prod
      MMI_CLIENT_ID: ${MMI_CLIENT_ID}
      MMI_CLIENT_SECRET: ${MMI_CLIENT_SECRET}
    ports:
      - 8000:8000
    expose:
      - 8000

  nginx:
    build:
      context: biap-app-ui-front
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
        REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
    container_name: biap-app-ui-front
    #    depends_on:
    #      - biap-bap-client
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
      REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
    depends_on:
      - mmi-client
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  certbot:
    image: certbot/certbot
    restart: "always"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  payment-service:
    build:
      context: biap-client-node-js
      dockerfile: Dockerfile
      args:
        JUSPAY_SECRET_KEY_PATH: ${JUSPAY_SECRET_KEY_PATH}
        JUSPAY_BASE_URL: ${JUSPAY_BASE_URL}
        JUSPAY_MERCHANT_ID: ${JUSPAY_MERCHANT_ID}
        JUSPAY_API_KEY: ${JUSPAY_API_KEY}
        FIREBASE_ADMIN_SERVICE_ACCOUNT: ${FIREBASE_ADMIN_SERVICE_ACCOUNT}
        ONDC_BASE_API_URL: ${ONDC_BASE_API_URL}
        PORT: 3000
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongo